name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lint

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  package:
    needs: [unit-test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  emulator:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: apk

      - name: Create Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6

      - name: Install APK on Emulator
        run: adb install app/build/outputs/apk/debug/app-debug.apk

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest
